# Les 2: Geavanceerde DataFrame Manipulaties met Pandas

Welkom terug! Vandaag gaan we dieper ingaan op enkele geavanceerde technieken voor het manipuleren van DataFrames in Pandas. We zullen de technieken `groupby`, pivot-tabellen en het samenvoegen van DataFrames verkennen, met behulp van een dataset over Spotify-artiesten.

## Stap 1: Importeren van Pandas

Eerst moeten we de Pandas-bibliotheek importeren. Pandas helpt ons om gemakkelijk met gegevens te werken.

In [18]:
import pandas as pd

## Stap 2: Onze gegevens

Laten we een dataset creëren over verschillende artiesten en hun nummers op Spotify. Deze dataset bevat informatie over de naam van de artiest, de titel van het nummer, het aantal streams en de prijs per stream.

In [19]:
# Onze gegevens
spotify_artiesten = {
    "Artiest": ["Drake", "Taylor Swift", "Ed Sheeran", "Billie Eilish", "BTS", "Ariana Grande"],
    "Titel": ["God's Plan", "Love Story", "Shape of You", "Bad Guy", "Dynamite", "7 rings"],
    "Streams": [1500000000, 300000000, 2600000000, 1900000000, 1700000000, 2100000000],
    "Prijs per stream": [0.004, 0.004, 0.004, 0.004, 0.004, 0.004],
}

# Omzetten van de dictionary naar een Pandas DataFrame
spotify_df = pd.DataFrame(spotify_artiesten)

# Bekijken van de eerste paar rijen van de DataFrame
spotify_df.head()

         Artiest         Titel     Streams  Prijs per stream
0          Drake    God's Plan  1500000000             0.004
1   Taylor Swift    Love Story   300000000             0.004
2     Ed Sheeran  Shape of You  2600000000             0.004
3  Billie Eilish       Bad Guy  1900000000             0.004
4            BTS      Dynamite  1700000000             0.004

## Stap 3: Verkennen van de DataFrame

Laten we eens kijken naar de structuur van onze DataFrame en de eerste paar rijen bekijken.

In [20]:
# Bekijk de structuur van de DataFrame
spotify_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Artiest           6 non-null      object
 1   Titel             6 non-null      object
 2   Streams           6 non-null      int64
 3   Prijs per stream  6 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 324.0+ bytes

<details>
  <summary style="background-color: #f0f8ff; border-left: 6px solid #1e90ff; padding: 10px; cursor: pointer;"><strong>Tip!</strong></summary>
  <div style="background-color: #f0f8ff; border-left: 6px solid #1e90ff; padding: 10px;">
    <ul>
      <li><code>pd.DataFrame(spotify_artiesten)</code> zet onze dictionary om in een tabel met rijen en kolommen.</li>
      <li><code>head()</code> toont de eerste paar rijen van de tabel, zodat we een idee krijgen van hoe onze gegevens eruitzien.</li>
      <li><code>info()</code> geeft ons informatie over het type gegevens in elke kolom en hoeveel niet-lege waarden er zijn.</li>
    </ul>
  </div>
</details>

## Stap 4: Eenvoudige bewerkingen

Laten we nu enkele eenvoudige bewerkingen uitvoeren op onze DataFrame. We beginnen met het berekenen van het totale aantal streams.

In [21]:
# Totale hoeveelheid streams
totaal_streams = spotify_df["Streams"].sum()
print(f"Totaal aantal streams: {totaal_streams}")

Totaal aantal streams: 10100000000

<details>
  <summary style="background-color: #f0f8ff; border-left: 6px solid #1e90ff; padding: 10px; cursor: pointer;"><strong>Tip!</strong></summary>
  <div style="background-color: #f0f8ff; border-left: 6px solid #1e90ff; padding: 10px;">
    <ul>
      <li><code>spotify_df["Streams"]</code> selecteert de kolom met het aantal streams.</li>
      <li><code>.sum()</code> berekent de som van alle waarden in deze kolom.</li>
    </ul>
  </div>
</details>

## Stap 5: Nieuwe kolom toevoegen

We gaan een nieuwe kolom toevoegen die de totale inkomsten voor elk nummer berekent (streams * prijs per stream).

In [22]:
# Nieuwe kolom 'Totale inkomsten' toevoegen
spotify_df['Totale inkomsten'] = spotify_df["Streams"] * spotify_df['Prijs per stream']

# Bekijken van de bijgewerkte DataFrame
spotify_df.head()

         Artiest         Titel     Streams  Prijs per stream  Totale inkomsten
0          Drake    God's Plan  1500000000             0.004         6000000.0
1   Taylor Swift    Love Story   300000000             0.004         1200000.0
2     Ed Sheeran  Shape of You  2600000000             0.004        10400000.0
3  Billie Eilish       Bad Guy  1900000000             0.004         7600000.0
4            BTS      Dynamite  1700000000             0.004         6800000.0

<details>
  <summary style="background-color: #f0f8ff; border-left: 6px solid #1e90ff; padding: 10px; cursor: pointer;"><strong>Tip!</strong></summary>
  <div style="background-color: #f0f8ff; border-left: 6px solid #1e90ff; padding: 10px;">
    <ul>
      <li>We vermenigvuldigen de waarden in de kolom "Streams" met de waarden in de kolom "Prijs per stream".</li>
      <li>De resultaten worden opgeslagen in een nieuwe kolom genaamd 'Totale inkomsten'.</li>
    </ul>
  </div>
</details>

## Stap 6: Groeperen en aggregeren

Laten we de gegevens groeperen op basis van de artiest en de totale streams per artiest berekenen.

In [25]:
# Groeperen op 'Artiest' en de som van de streams berekenen
groepering = spotify_df.groupby('Artiest')["Streams"].sum()
groepering

Artiest
Ariana Grande    2100000000
BTS              1700000000
Billie Eilish    1900000000
Drake            1500000000
Ed Sheeran       2600000000
Taylor Swift      300000000
Name: Streams, dtype: int64

<details>
  <summary style="background-color: #f0f8ff; border-left: 6px solid #1e90ff; padding: 10px; cursor: pointer;"><strong>Tip!</strong></summary>
  <div style="background-color: #f0f8ff; border-left: 6px solid #1e90ff; padding: 10px;">
    <ul>
      <li><code>groupby('Artiest')</code> groepeert de rijen van de DataFrame op basis van de waarden in de kolom 'Artiest'.</li>
      <li><code>sum()</code> berekent de som van de "Streams" binnen elke groep artiesten.</li>
    </ul>
  </div>
</details>

## Stap 7: Pivot-tabellen

We maken een pivot-tabel om de totale inkomsten voor elke artiest te bekijken.

In [26]:
# Maak een pivot-tabel
pivot_tabel = spotify_df.pivot_table(values='Totale inkomsten', index='Artiest', aggfunc='sum')
pivot_tabel

               Totale inkomsten
Artiest
Ariana Grande         8400000.0
BTS                   6800000.0
Billie Eilish         7600000.0
Drake                 6000000.0
Ed Sheeran           10400000.0
Taylor Swift          1200000.0

<details>
  <summary style="background-color: #f0f8ff; border-left: 6px solid #1e90ff; padding: 10px; cursor: pointer;"><strong>Tip!</strong></summary>
  <div style="background-color: #f0f8ff; border-left: 6px solid #1e90ff; padding: 10px;">
    <ul>
      <li><code>pivot_table</code> maakt een nieuwe tabel (pivot-tabel) waarbij de rijen worden gegroepeerd op basis van de waarde in de kolom 'Artiest'.</li>
      <li><code>values='Totale inkomsten'</code> specificeert de kolom waarvan we de waarden willen gebruiken.</li>
      <li><code>aggfunc='sum'</code> specificeert dat we de waarden willen sommeren.</li>
    </ul>
  </div>
</details>

## Stap 8: DataFrames samenvoegen

Stel dat we een tweede dataset hebben met informatie over de muzieklabels van de artiesten. We gaan deze datasets samenvoegen.

In [28]:
# Tweede dataset met informatie over muzieklabels
muzieklabels = {
    "Artiest": ["Drake", "Taylor Swift", "Ed Sheeran", "Billie Eilish", "BTS", "Ariana Grande"],
    "Label": ["Universal", "Republic", "Atlantic", "Interscope", "Big Hit", "Republic"]
}

labels_df = pd.DataFrame(muzieklabels)

# Samenvoegen van de twee DataFrames
samengevoegd_df = pd.merge(spotify_df, labels_df, on="Artiest")
samengevoegd_df

,Artiest,Titel,Streams,Prijs per stream,Totale inkomsten,Label
0,Drake,God's Plan,1500000000,0.004,6000000.0,Universal
1,Taylor Swift,Love Story,300000000,0.004,1200000.0,Republic
2,Ed Sheeran,Shape of You,2600000000,0.004,10400000.0,Atlantic
3,Billie Eilish,Bad Guy,1900000000,0.004,7600000.0,Interscope
4,BTS,Dynamite,1700000000,0.004,6800000.0,Big Hit
5,Ariana Grande,7 rings,2100000000,0.004,8400000.0,Republic

<details>
  <summary style="background-color: #f0f8ff; border-left: 6px solid #1e90ff; padding: 10px; cursor: pointer;"><strong>Tip!</strong></summary>
  <div style="background-color: #f0f8ff; border-left: 6px solid #1e90ff; padding: 10px;">
    <ul>
      <li>We creëren een nieuwe DataFrame <code>labels_df</code> met informatie over de muzieklabels van elk type artiest.</li>
      <li><code>pd.merge(spotify_df, labels_df, on="Artiest")</code> voegt de twee DataFrames samen op basis van de gemeenschappelijke kolom 'Artiest'.</li>
    </ul>
  </div>
</details>

## Conclusie

In deze les hebben we geleerd hoe we geavanceerde DataFrame manipulatietechnieken kunnen